import {useEffect,useMemo,useState} from 'react';
import type {ActiveConfig,Attachment,Reading,Snapshot} from './types';

const API=import.meta.env.VITE_API_URL??'';
type View='performance'|'monitor'|'maintenance';
type Skin='mirage-vfd'|'diagnostic-green';
type Widget='boost'|'temperatures'|'tires'|'afr';
type Preferences={view:View;skin:Skin;widgets:Record<Widget,boolean>};
const defaultPreferences:Preferences={view:'monitor',skin:'diagnostic-green',widgets:{boost:true,temperatures:true,tires:true,afr:true}};
const fallback:ActiveConfig={vehicle:{id:'fk8',displayName:'Honda Civic Type R FK8',osName:'FK8 OS',redlineRpm:7000,warningThresholds:{coolantTempHigh:220,oilTempHigh:260,oilPressureLow:15,batteryVoltageLow:11.8},shiftLights:{startRpm:5500,warningRpm:6500,redlineRpm:7000}},theme:{id:'mirage-retro',name:'Mirage Retro',colors:{background:'#020506',panel:'#071012',foreground:'#caffdf',muted:'#477766',accent:'#32f58d',secondary:'#55f6ec',warning:'#ffb547',critical:'#ff3f79',sunset:'#ff8451'},fontDisplay:'DIN Condensed, Avenir Next Condensed, ui-monospace, monospace',glowStrength:.38,scanlineStrength:.1},client:{name:'Mirage Motorworks',systemName:'Mirage Telemetry OS',tagline:'Machines with a past. Built for the road ahead.',startupText:'MIRAGE MOTORWORKS',footerText:'MIRAGE MOTORWORKS // VEHICLE SYSTEMS'}};

function readPreferences():Preferences{try{return {...defaultPreferences,...JSON.parse(localStorage.getItem('mirage-display')??'{}')}}catch{return defaultPreferences}}
function useTelemetry(){const[data,setData]=useState<Snapshot>();const[online,setOnline]=useState(false);useEffect(()=>{let ws:WebSocket,timer:number,closed=false;const connect=()=>{ws=new WebSocket((API||location.origin).replace(/^http/,'ws')+'/ws/telemetry');ws.onopen=()=>setOnline(true);ws.onmessage=e=>setData(JSON.parse(e.data));ws.onclose=()=>{setOnline(false);if(!closed)timer=window.setTimeout(connect,1200)}};connect();return()=>{closed=true;clearTimeout(timer);ws?.close()}},[]);return{data,online}}
export const formatReading=(r?:Reading,digits=0)=>r?.available&&r.value!=null?r.value.toFixed(digits):'—';
export const needsAttachmentScreen=(state?:string)=>state!=='CONNECTED';

function Shift({rpm=0,config}:{rpm?:number;config:ActiveConfig}){return <div className="shift" aria-label="shift lights">{Array.from({length:12},(_,i)=>{const threshold=config.vehicle.shiftLights.startRpm+i*(config.vehicle.redlineRpm-config.vehicle.shiftLights.startRpm)/11;return <i key={i} className={rpm>=threshold?(threshold>=config.vehicle.shiftLights.warningRpm?'hot':'on'):''}/>})}</div>}
function Metric({label,reading,unit,tone}:{label:string;reading?:Reading;unit:string;tone?:string}){return <section className={'metric '+(tone??'')}><span>{label}</span><strong>{formatReading(reading,unit==='V'||unit==='AFR'?1:0)}</strong><small>{reading?.available?unit:'NO SIGNAL'}</small></section>}

const adapterField=(attachment:Attachment,key:'Name'|'Port'|'Protocol')=>attachment.adapter[key]??attachment.adapter[key.toLowerCase() as 'name'|'port'|'protocol']??'UNKNOWN';
function AttachExperience({attachment,online}:{attachment?:Attachment;online:boolean}){const state=attachment?.state??'STARTING';const action=(value:string)=>fetch(API+'/api/simulator/action',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({action:value})});const capabilities=Object.entries(attachment?.capabilities??{});return <main className="attach-shell"><section className="attach-console"><div className="attach-mark">M</div><p>MIRAGE MOTORWORKS</p><h1>VEHICLE INTERFACE 01</h1><div className="attach-state">{state.replaceAll('_',' ')}</div><p className="attach-message">{attachment?.message??'Starting telemetry services...'}</p><div className="attach-lines"><div><span>SERIAL BUS</span><b>{attachment&&adapterField(attachment,'Port')!=='UNKNOWN'?'ONLINE':'WAITING'}</b></div><div><span>ADAPTER</span><b>{attachment?adapterField(attachment,'Name'):'PROBING'}</b></div><div><span>DIAGNOSTIC LINK</span><b>{attachment?.ecuConnected?'ESTABLISHED':'STANDBY'}</b></div><div><span>VEHICLE ID</span><b>{attachment?.identity?.manufacturer?.value??'UNKNOWN'}</b></div><div><span>TELEMETRY MAP</span><b>{attachment?.supportedMetrics??0} CHANNELS</b></div><div><span>PROFILE</span><b>{attachment?.profile?.profileId?.toUpperCase()??'GENERIC'}</b></div></div>{attachment?.identity?.model?.value&&attachment.identity.model.value!=='UNKNOWN'&&<div className="vehicle-acquired"><strong>{attachment.identity.manufacturer.value} {attachment.identity.model.value}</strong><span>{attachment.identity.generation.value} // MY{attachment.identity.modelYear.value}</span><small>{adapterField(attachment,'Protocol')}</small></div>}{capabilities.length>0&&<div className="capability-grid">{capabilities.slice(0,16).map(([name,cap])=><span className={cap.available?'yes':'no'} key={name}>{name.replace(/([A-Z])/g,' $1')} <b>{cap.available?'YES':'NO / UNKNOWN'}</b></span>)}</div>}<div className="dev-actions"><button onClick={()=>action('attach-adapter')}>ATTACH USB</button><button onClick={()=>action('remove-adapter')}>REMOVE USB</button><button onClick={()=>action('attach-fk8')}>FK8</button><button onClick={()=>action('attach-fl5')}>FL5</button><button onClick={()=>action('attach-bronco')}>BRONCO</button><button onClick={()=>action('attach-generic')}>GENERIC</button><button onClick={()=>action('ignition-off')}>IGNITION OFF</button><button onClick={()=>action('partial-pid-support')}>PARTIAL PIDS</button></div><footer><span>TELEMETRY SERVICE {online?'ONLINE':'RECONNECTING'}</span><span>READ-ONLY DIAGNOSTIC MODE</span></footer></section></main>}

function Boot({cfg,onComplete}:{cfg:ActiveConfig;onComplete:()=>void}){const[phase,setPhase]=useState(0);useEffect(()=>{const key=(e:KeyboardEvent)=>{if(e.code==='Space'&&phase===0){e.preventDefault();setPhase(1)}};window.addEventListener('keydown',key);return()=>window.removeEventListener('keydown',key)},[phase]);useEffect(()=>{if(phase===0)return;const delays=phase===1?850:phase===2?1050:1250;const timer=window.setTimeout(()=>phase===3?onComplete():setPhase(v=>v+1),delays);return()=>clearTimeout(timer)},[phase]);return <main className="boot tunnel-background"><div className="boot-shade"/><div className="boot-console"><div className="mark">M</div><p>{cfg.client.startupText}</p><h1 key={phase>=2?'fk8':'unknown'} className={phase>=2?'vehicle-id detected':'vehicle-id'}>{phase>=2?cfg.vehicle.osName:'____ OS'}</h1><div className={'bootline '+(phase>=1?'complete':'')}><b>{phase>=1?'✓':'□'}</b><span>{phase===0?'OBD INTERFACE STANDBY':'OBD INTERFACE CONNECTED'}</span></div><div className={'bootline '+(phase>=2?'complete':'')}><b>{phase>=2?'✓':'□'}</b><span>{phase<2?'READING VEHICLE ID':'VEHICLE PROFILE: FK8'}</span></div><div className={'bootline '+(phase>=3?'complete':'')}><b>{phase>=3?'✓':'□'}</b><span>{phase<3?'VERIFYING TELEMETRY CHANNELS':'TELEMETRY CHANNELS READY'}</span></div>{phase===0?<button className="space-prompt" onClick={()=>setPhase(1)}>PRESS SPACE TO CONNECT</button>:<small className="boot-progress">{phase===1?'QUERYING ECU...':phase===2?'LOADING FK8 PROFILE...':'INITIALIZATION COMPLETE'}</small>}</div></main>}

function Performance({data,cfg}:{data?:Snapshot;cfg:ActiveConfig}){const rpm=data?.rpm.value??0;return <><div className="tach-label"><span>ENGINE RPM × 1000</span><span>SHIFT MONITOR</span></div><Shift rpm={rpm??0} config={cfg}/><div className="dashboard"><section className="rpm"><div className="eyebrow">ENGINE SPEED <span>RPM</span></div><strong>{Math.round(rpm??0).toLocaleString()}</strong><div className="rpmbar"><i style={{width:`${Math.min(100,(rpm??0)/cfg.vehicle.redlineRpm*100)}%`}}/></div><div className="scale"><span>0</span><span>1</span><span>2</span><span>3</span><span>4</span><span>5</span><span>6</span><span>{cfg.vehicle.redlineRpm/1000}</span></div></section><section className="speed"><span>DIGITAL SPEED</span><strong>{formatReading(data?.vehicle_speed_mph)}</strong><small>M P H</small></section><section className="gear"><span>RANGE</span><strong>{formatReading(data?.gear)}</strong><small>GEAR</small></section><Metric label="MANIFOLD BOOST" reading={data?.boost_psi} unit="PSI" tone="cyan"/><Metric label="ENGINE OIL" reading={data?.oil_temp_f} unit="°F"/><Metric label="ENGINE COOLANT" reading={data?.coolant_temp_f} unit="°F"/><Metric label="INTAKE AIR" reading={data?.intake_air_temp_f} unit="°F"/><Metric label="THROTTLE POSITION" reading={data?.throttle_percent} unit="%" tone="cyan"/><Metric label="AIR / FUEL" reading={data?.afr} unit="AFR"/><Metric label="SYSTEM VOLTS" reading={data?.battery_voltage} unit="V"/></div></>}

function Bar({value,max=100}:{value:number;max?:number}){const blocks=20,active=Math.round(Math.min(1,value/max)*blocks);return <div className="block-bar" aria-label={`${value} of ${max}`}>{Array.from({length:blocks},(_,i)=><i className={i<active?'lit':''} key={i}/>)}</div>}
function TireDiagram(){return <div className="tire-system"><div className="tire-value lf"><span><b>LF</b><strong>35</strong><small>PSI</small></span><i/></div><div className="tire-value rf"><span><b>RF</b><strong>35</strong><small>PSI</small></span><i/></div><img className="car-wireframe" src="/assets/vehicle-wireframe.png" alt="Top-down vehicle tire-position diagram"/><div className="tire-value lr"><span><b>LR</b><strong>33</strong><small>PSI</small></span><i/></div><div className="tire-value rr"><span><b>RR</b><strong>33</strong><small>PSI</small></span><i/></div></div>}
function Monitor({data,widgets}:{data?:Snapshot;widgets:Preferences['widgets']}){const boost=data?.boost_psi.value??0;return <div className="monitor-page"><div className="monitor-title"><span>VEHICLE SYSTEM MONITOR</span><b>PAGE 01</b></div>{widgets.boost&&<section className="boost-strip"><div><span>MANIFOLD BOOST</span><strong>{formatReading(data?.boost_psi,1)} <small>PSI</small></strong></div><Bar value={Math.max(0,boost)} max={24}/></section>} {widgets.temperatures&&<div className="monitor-stats"><Metric label="OIL TEMP" reading={data?.oil_temp_f} unit="°F"/><Metric label="COOLANT" reading={data?.coolant_temp_f} unit="°F"/><Metric label="INTAKE" reading={data?.intake_air_temp_f} unit="°F"/>{widgets.afr&&<Metric label="AIR / FUEL" reading={data?.afr} unit="AFR"/>}</div>}{widgets.tires&&<section className="tires"><div className="section-label">TIRE PRESSURE MONITOR // SIMULATED</div><TireDiagram/></section>}<div className="system-nominal">SYSTEM STATUS: <b>NOMINAL</b></div></div>}

function HealthRow({label,value,status}:{label:string;value:number;status:string}){return <section className="health-row"><div><span>{label}</span><small>{status}</small></div><strong>{value}<small>%</small></strong><Bar value={value}/></section>}
function Maintenance({data}:{data?:Snapshot}){return <div className="maintenance-page"><div className="monitor-title"><span>MAINTENANCE STATUS</span><b>PAGE 02</b></div><div className="service-summary"><div className="service-icon">◆</div><div><span>NEXT SERVICE</span><strong>2,480 <small>MI</small></strong><p>ESTIMATED // SIMULATED DATA</p></div></div><HealthRow label="ENGINE OIL LIFE" value={87} status="SERVICE NOT REQUIRED"/><HealthRow label="FRONT BRAKE PADS" value={76} status="WITHIN SPECIFICATION"/><HealthRow label="REAR BRAKE PADS" value={81} status="WITHIN SPECIFICATION"/><HealthRow label="BATTERY HEALTH" value={94} status={`${formatReading(data?.battery_voltage,1)} V // HEALTHY`}/><div className="maintenance-note">NO ACTIVE MAINTENANCE ITEMS</div></div>}

function Settings({prefs,setPrefs,close}:{prefs:Preferences;setPrefs:(p:Preferences)=>void;close:()=>void}){const set=<K extends keyof Preferences>(key:K,value:Preferences[K])=>setPrefs({...prefs,[key]:value});return <div className="settings-backdrop" role="dialog" aria-modal="true" aria-label="Display configuration"><aside className="settings-panel"><header><div><span>DEBUG // DISPLAY CONFIGURATION</span><small>LOCAL OPERATOR CONSOLE</small></div><button onClick={close}>ESC</button></header><section><h2>ACTIVE DISPLAY</h2>{(['performance','monitor','maintenance'] as View[]).map(v=><button className={prefs.view===v?'selected':''} onClick={()=>set('view',v)} key={v}><b>{v==='performance'?'01':v==='monitor'?'02':'03'}</b>{v.toUpperCase()}</button>)}</section><section><h2>DISPLAY THEME</h2><button className={prefs.skin==='mirage-vfd'?'selected':''} onClick={()=>set('skin','mirage-vfd')}><b>A</b>MIRAGE VFD</button><button className={prefs.skin==='diagnostic-green'?'selected':''} onClick={()=>set('skin','diagnostic-green')}><b>B</b>DIAGNOSTIC GREEN</button></section><section><h2>MONITOR MODULES</h2>{(Object.keys(prefs.widgets) as Widget[]).map(w=><label key={w}><input type="checkbox" checked={prefs.widgets[w]} onChange={e=>set('widgets',{...prefs.widgets,[w]:e.target.checked})}/><i/>{w.toUpperCase()}</label>)}</section><footer><span>F2 OR ⌘, TO TOGGLE</span><span>CHANGES SAVE AUTOMATICALLY</span></footer></aside></div>}

export function App(){const[cfg,setCfg]=useState(fallback);const{data,online}=useTelemetry();const[boot,setBoot]=useState(false);const[settings,setSettings]=useState(false);const[prefs,setPrefsState]=useState<Preferences>(readPreferences);const setPrefs=(p:Preferences)=>{setPrefsState(p);localStorage.setItem('mirage-display',JSON.stringify(p))};useEffect(()=>{fetch(API+'/api/config/active').then(r=>r.ok?r.json():Promise.reject()).then(setCfg).catch(()=>{})},[]);useEffect(()=>{const key=(e:KeyboardEvent)=>{if(e.key==='F2'||((e.metaKey||e.ctrlKey)&&e.key===',')){e.preventDefault();setSettings(v=>!v)}else if(e.key==='Escape')setSettings(false);else if(!settings&&['1','2','3'].includes(e.key))setPrefs({...prefs,view:e.key==='1'?'performance':e.key==='2'?'monitor':'maintenance'})};window.addEventListener('keydown',key);return()=>window.removeEventListener('keydown',key)},[settings,prefs]);useEffect(()=>{const root=document.documentElement;Object.entries(cfg.theme.colors).forEach(([k,v])=>root.style.setProperty('--'+k,v));root.style.setProperty('--display',cfg.theme.fontDisplay);root.dataset.skin=prefs.skin},[cfg,prefs.skin]);const warnings=useMemo(()=>{if(!data)return[];const w:string[]=[];if(!online||!data.provider_connected)w.push('TELEMETRY PROVIDER OFFLINE');if((data.coolant_temp_f.value??0)>cfg.vehicle.warningThresholds.coolantTempHigh)w.push('COOLANT TEMPERATURE HIGH');if((data.oil_temp_f.value??0)>cfg.vehicle.warningThresholds.oilTempHigh)w.push('OIL TEMPERATURE HIGH');if(data.oil_pressure_psi.available&&(data.oil_pressure_psi.value??99)<cfg.vehicle.warningThresholds.oilPressureLow)w.push('OIL PRESSURE LOW');return w},[data,online,cfg]);if(!data||needsAttachmentScreen(data.attachment?.state))return <AttachExperience attachment={data?.attachment} online={online}/>;if(boot)return <Boot cfg={cfg} onComplete={()=>setBoot(false)}/>;if(settings)return <Settings prefs={prefs} setPrefs={setPrefs} close={()=>setSettings(false)}/>;return <main className="shell"><div className="dash-frame"><header><div className="brand"><span className="mini-mark">M</span><div><b>{data.attachment.profile.osName||cfg.vehicle.osName}</b><small>ELECTRONIC INSTRUMENTATION</small></div></div><div className="header-center">{prefs.view.toUpperCase()} DISPLAY</div><div className="status"><i className={online?'ok':''}/>{online?'SYSTEM ONLINE':'RECONNECTING'}</div></header>{warnings.length>0&&<div className="warning">◆ {warnings.join(' // ')}</div>}{prefs.view==='performance'&&<Performance data={data} cfg={cfg}/>} {prefs.view==='monitor'&&<Monitor data={data} widgets={prefs.widgets}/>} {prefs.view==='maintenance'&&<Maintenance data={data}/>}<footer><span>{cfg.client.footerText}</span><span>1 PERFORMANCE · 2 MONITOR · 3 MAINTENANCE</span><button onClick={()=>setSettings(true)}>F2 // CONFIGURE</button></footer></div></main>}
