INSERT INTO vehicles (
    id,
    slug,
    year,
    make,
    model,
    trim,
    status,
    mileage,
    exterior_color,
    interior_color,
    transmission,
    drivetrain,
    engine,
    asking_price,
    invested_amount,
    projected_profit,
    days_in_inventory,
    hero_image,
    gallery,
    highlights,
    story,
    inspection_notes
) VALUES
(
    '11111111-1111-1111-1111-111111111111',
    '2021-honda-civic-type-r',
    2021,
    'Honda',
    'Civic Type R',
    'FK8 Touring Edition',
    'available',
    28600,
    'Championship White',
    'Black and Red',
    '6-speed manual',
    'FWD',
    '2.0L Turbocharged Inline-Four',
    50000,
    43000,
    7000,
    6,
    '/vehicles/type-r/hero.jpg',
    ARRAY[
        '/vehicles/type-r/front.jpg',
        '/vehicles/type-r/side.jpg',
        '/vehicles/type-r/rear.jpg'
    ],
    ARRAY[
        'Championship White over red-accented cabin',
        '6-speed manual',
        'Track-bred FK8 chassis',
        'Aggressive aero and stance'
    ],
    'A 2021 Civic Type R with the kind of presence that made the FK8 impossible to ignore: serious pace, manual control, and a personality that still feels wonderfully unfiltered.',
    'Initial presentation review complete. Mechanical inspection, paint readings, and service documentation are queued before final dossier release.'
),
(
    '22222222-2222-2222-2222-222222222222',
    '2013-chevrolet-camaro-2ss',
    2013,
    'Chevrolet',
    'Camaro',
    '2SS Coupe',
    'available',
    41200,
    'Black',
    'Black Leather',
    '6-speed manual',
    'RWD',
    '6.2L LS3 V8',
    50000,
    41000,
    9000,
    4,
    '/vehicles/camaro/hero.jpg',
    ARRAY[
        '/vehicles/camaro/front.jpg',
        '/vehicles/camaro/detail.jpg',
        '/vehicles/camaro/rear.jpg'
    ],
    ARRAY[
        '2SS V8 coupe',
        'Black-on-black presentation',
        'Wide, low stance',
        'Analog muscle-car character'
    ],
    'A 2013 Camaro 2SS with the right visual weight: black paint, V8 attitude, and a simple brief. Big displacement, rear drive, and drama without apology.',
    'Cosmetic photo review complete. Mechanical inspection, tire/brake measurements, and service documentation are queued before final dossier release.'
);
